coverage:
  round: down
  precision: 2
comments: off
fixes:
  - "virtualenv/python*/lib/python*/site-packages/::src/"
  - "venv-nbbook/lib/python*/site-packages/::src/"
  - "home/travis/virtualenv/python*/lib/python*/site-packages/::src/"

